version: "3.9"

services:
  next-tester:
    build: .
    image: next-tester
    container_name: next-tester
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped